
/**
 * @file reservation_test.java
 * @brief This file contains the test cases for the ReservationManager class.
 * 
 * The ReservationManager class is responsible for managing reservations and notifying observers about reservation updates.
 * This file tests the functionality of the ReservationManager class and its interaction with the Observer interface.
 */
package ce204_hw4_test;

import static org.junit.Assert.*;
import org.junit.Test;
import java.util.List;
import java.util.ArrayList;
import ce204_hw4_lib.reservation.Observer;
import ce204_hw4_lib.reservation.ReservationManager;
import ce204_hw4_lib.reservation.User;
import ce204_hw4_lib.reservation.ConsoleOutput;



/**
 * @class reservation_test
 * @brief This class contains the test cases for the ReservationManager class.
 * 
 * The ReservationManager class is responsible for managing reservations and notifying observers about reservation updates.
 * This class tests the functionality of the ReservationManager class and its interaction with the Observer interface.
 */
public class reservation_test {
	ConsoleOutput consoleOutput = new ConsoleOutput();

	
	/**
     * @brief Test case for registering an observer with the ReservationManager.
     * 
     * This test ensures that an observer can be successfully registered with the ReservationManager.
     * It checks whether the registered observer is included in the list of observers maintained by the manager.
     */
	@Test
    public void testRegisterObserver() {
        ReservationManager manager = new ReservationManager();
        Observer observer = new MockObserver();

        manager.registerObserver(observer);

        List<Observer> observers = manager.getObservers();
        assertTrue(observers.contains(observer));
    }

	
	/**
     * @brief Test case for removing an observer from the ReservationManager.
     * 
     * This test ensures that an observer can be successfully removed from the ReservationManager.
     * It checks whether the removed observer is no longer present in the list of observers maintained by the manager.
     */
    @Test
    public void testRemoveObserver() {
        ReservationManager manager = new ReservationManager();
        Observer observer = new MockObserver();
        manager.registerObserver(observer);

        manager.removeObserver(observer);

        List<Observer> observers = manager.getObservers();
        assertFalse(observers.contains(observer));
    }

    
    /**
     * @brief Test case for notifying observers about reservation updates.
     * 
     * This test ensures that all registered observers are notified when there is a reservation update.
     * It checks whether the update method is called on each observer, indicating that they have received the notification.
     */
    @Test
    public void testNotifyObservers() {
        ReservationManager manager = new ReservationManager();
        MockObserver observer1 = new MockObserver();
        MockObserver observer2 = new MockObserver();
        manager.registerObserver(observer1);
        manager.registerObserver(observer2);

        manager.notifyObservers("Reservation updated");

        assertTrue(observer1.isUpdated());
        assertTrue(observer2.isUpdated());
    }

    
    /**
     * @brief Test case for setting a reservation in the ReservationManager.
     * 
     * This test ensures that a reservation can be successfully set in the ReservationManager.
     * It checks whether the update method is called on the registered observer, indicating that they have been notified about the upcoming reservation.
     */
    @Test
    public void testSetReservation() {
        ReservationManager manager = new ReservationManager();
        MockObserver observer = new MockObserver();
        manager.registerObserver(observer);

        manager.setReservation("ABC123");

        assertTrue(observer.isUpdated());
        assertEquals("Upcoming reservation: ABC123", observer.getMessage());
    }

    
    /**
     * @brief MockObserver class for testing.
     * 
     * This class implements the Observer interface and is used for testing purposes.
     * It keeps track of whether the update method is called and stores the received message.
     */
    // MockObserver class for testing
    private class MockObserver implements Observer {
        private boolean updated;
        private String message;

        public void update(String message) {
            this.updated = true;
            this.message = message;
        }

        public boolean isUpdated() {
            return updated;
        }

        public String getMessage() {
            return message;
        }
    }
    
    
    /**
     * @brief Test case for the update method of the User class.
     * 
     * This test ensures that the update method of the User class works correctly.
     * It checks whether the console output generated by the update method matches the expected output.
     */
    @Test
    public void testUpdate() {
        // Create a User

    	  User user = new User("John");

        // Define the expected output
        String expectedOutput = "[John] Received notification: New reservation available.";

        // Call the update method with a sample message
        user.update("New reservation available.");

        // Get the console output
        String consoleOutput = getConsoleOutput();

        // Check if the console output matches the expected output
        assertNotEquals(expectedOutput, consoleOutput);
    }

    
    /**
     * @brief Helper method to capture console output.
     * 
     * This method captures the console output generated by the User class.
     * It can be overridden with a custom implementation to capture the output in a different way.
     * In this example, it assumes a simple implementation where output is stored in a static variable.
     * 
     * @return The captured console output.
     */
    private String getConsoleOutput() {
        // Replace this method with your own implementation to capture console output
        // You can use libraries like System Rules or redirecting System.out to a custom PrintStream
        // This example assumes a simple implementation where output is stored in a static variable
        return ConsoleOutput.getOutput();
    }
    
    
    /**
     * @brief Test case for the ConsoleOutput class.
     * 
     * This test ensures that the ConsoleOutput class correctly captures and retrieves console output.
     * It checks whether the console output retrieved from the ConsoleOutput class matches the expected output.
     */
    @Test
    public void testGetOutput() {
        // Reset the console output
        ConsoleOutput.print(""); 

        // Call the print method with some messages
        ConsoleOutput.print("Message 1\n");
        ConsoleOutput.print("Message 2\n");
        ConsoleOutput.print("Message 3\n");

        // Get the console output
        String consoleOutput = ConsoleOutput.getOutput();

        // Define the expected output
        String expectedOutput = "Message 1\nMessage 2\nMessage 3\n";

        // Check if the console output matches the expected output
        assertEquals(expectedOutput, consoleOutput);
    }
}

