Rent Car Application with Library: ce204_hw4_app.Menus.VendorMenu Class Reference
ce204_hw4_app.Menus.VendorMenu Class Reference
Represents a menu for vendor-related actions in the car rental application.
Public Member Functions
VendorMenu (App app)
Constructs a new VendorMenu object.
void run ()
Executes the main functionality of the class.
Public Member Functions inherited from ce204_hw4_app.Menus.Menu
Menu (App app)
Constructs a new Menu object.
Additional Inherited Members
Protected Attributes inherited from ce204_hw4_app.Menus.Menu
App app
Constructor method for the Menu class.
Scanner scanner
Scanner object for input.
Detailed Description
Represents a menu for vendor-related actions in the car rental application.
Definition at line 26 of file VendorMenu.java.
Constructor & Destructor Documentation
VendorMenu()
ce204_hw4_app.Menus.VendorMenu.VendorMenu (App app)
Constructs a new VendorMenu object.
Parameters
app The App object representing the car rental application.
Definition at line 41 of file VendorMenu.java.
{
     super(app);
     cars = app.getCars();
     vendors = app.getVendors();
   }
References ce204_hw4_app.Menus.Menu.app, ce204_hw4_app.App.getCars(), and ce204_hw4_app.App.getVendors().
Member Function Documentation
run()
void ce204_hw4_app.Menus.VendorMenu.run ()
Executes the main functionality of the class.
This method represents the main entry point of the class and is responsible for executing its core functionality. It displays a menu for vendors, allowing them to add or remove cars, or exit the menu. The user's choice is read from the input using a Scanner object. Based on the chosen option, the corresponding method is called to perform the requested action. The loop continues until the user chooses to exit the menu.
Reimplemented from ce204_hw4_app.Menus.Menu.
Definition at line 56 of file VendorMenu.java.
                     {
     boolean exitVendorMenu = false;
     while (!exitVendorMenu) {
       System.out.println("------------------------------------------------");
       System.out.println("Vendor Menu");
       System.out.println("1. Add Car");
       System.out.println("2. Remove Car");
       System.out.println("3. Exit");
       System.out.println("------------------------------------------------");
       System.out.print("Enter your choice: ");
       int choice = scanner.nextInt();
       scanner.nextLine(); // Consume the newline character
       switch (choice) {
         case 1:
           addCar();
           break;
         case 2:
           removeCar();
           break;
         case 3:
           exitVendorMenu = true;
           System.out.println("Exiting Vendor Menu...");
           break;
         default:
           System.out.println("Invalid choice. Please try again.");
           break;
       }
     }
     // Return to the role selection menu after exiting the vendor menu
     app.setMainMenu();
   }
References ce204_hw4_app.Menus.Menu.app, ce204_hw4_app.Menus.Menu.scanner, and ce204_hw4_app.App.setMainMenu().
The documentation for this class was generated from the following file:
ce204_hw4/src/main/java/ce204_hw4_app/Menus/VendorMenu.java