Rent Car Application with Library: ce204_hw4_app.App Class Reference
ce204_hw4_app.App Class Reference
This is the application class. This class manages the main logic of the rental application, listing the cars and vendors, and allowing navigation between menus.
Public Member Functions
App (Scanner scanner)
Constructor for the App.java class.
void runMenu ()
Runs the menu and allows the user to navigate between menus.
List< Car > getCars ()
Returns the list of cars.
List< Vendor > getVendors ()
Returns the list of vendors.
void setMenu (Menu menu)
Sets the selected menu.
void setMainMenu ()
Sets the main menu as the selected menu.
void setVendorMenu ()
Sets the vendor menu as the selected menu.
void setUserMenu ()
Sets the user menu as the selected menu.
Public Attributes
Menu selectedMenu
The currently selected menu.
Scanner scanner
The user menu object.
Detailed Description
This is the application class. This class manages the main logic of the rental application, listing the cars and vendors, and allowing navigation between menus.
Definition at line 27 of file App.java.
Constructor & Destructor Documentation
App()
ce204_hw4_app.App.App (Scanner scanner)
Constructor for the App.java class.
Parameters
scanner A Scanner object used to get user input.
Definition at line 70 of file App.java.
{
         this.scanner = scanner;
         cars = new ArrayList<>();
         vendors = new ArrayList<>();
         mainMenu = new MainMenu(this);
         vendorMenu = new VendorMenu(this);
         userMenu = new UserMenu(this);
         selectedMenu = mainMenu;
     }
References ce204_hw4_app.App.scanner, and ce204_hw4_app.App.selectedMenu.
Member Function Documentation
getCars()
List<Car> ce204_hw4_app.App.getCars ()
Returns the list of cars.
Returns
A list of Car objects containing the cars.
Definition at line 94 of file App.java.
{
         return cars;
     }
Referenced by ce204_hw4_app.Menus.UserMenu.UserMenu(), and ce204_hw4_app.Menus.VendorMenu.VendorMenu().
getVendors()
List<Vendor> ce204_hw4_app.App.getVendors ()
Returns the list of vendors.
Returns
A list of Vendor objects containing the vendors.
Definition at line 103 of file App.java.
{
         return vendors;
     }
Referenced by ce204_hw4_app.Menus.VendorMenu.VendorMenu().
runMenu()
void ce204_hw4_app.App.runMenu ()
Runs the menu and allows the user to navigate between menus.
Definition at line 83 of file App.java.
{
         while (Main.isRunning) {
             selectedMenu.run();
         }
     }
References ce204_hw4_app.Main.isRunning, ce204_hw4_app.Menus.Menu.run(), and ce204_hw4_app.App.selectedMenu.
Referenced by ce204_hw4_app.Main.main().
setMainMenu()
void ce204_hw4_app.App.setMainMenu ()
Sets the main menu as the selected menu.
Definition at line 119 of file App.java.
{
         selectedMenu = mainMenu;
     }
References ce204_hw4_app.App.selectedMenu.
Referenced by ce204_hw4_app.Menus.UserMenu.run(), and ce204_hw4_app.Menus.VendorMenu.run().
setMenu()
void ce204_hw4_app.App.setMenu (Menu menu)
Sets the selected menu.
Parameters
menu The menu object to be set.
Definition at line 112 of file App.java.
{
         this.selectedMenu = menu;
     }
setUserMenu()
void ce204_hw4_app.App.setUserMenu ()
Sets the user menu as the selected menu.
Definition at line 133 of file App.java.
{
         selectedMenu = userMenu;
     }
References ce204_hw4_app.App.selectedMenu.
Referenced by ce204_hw4_app.Menus.MainMenu.run().
setVendorMenu()
void ce204_hw4_app.App.setVendorMenu ()
Sets the vendor menu as the selected menu.
Definition at line 126 of file App.java.
{
         selectedMenu = vendorMenu;
     }
References ce204_hw4_app.App.selectedMenu.
Referenced by ce204_hw4_app.Menus.MainMenu.run().
Member Data Documentation
scanner
Scanner ce204_hw4_app.App.scanner
The user menu object.
Definition at line 62 of file App.java.
Referenced by ce204_hw4_app.App.App(), and ce204_hw4_app.Menus.Menu.Menu().
selectedMenu
Menu ce204_hw4_app.App.selectedMenu
The currently selected menu.
Definition at line 42 of file App.java.
Referenced by ce204_hw4_app.App.App(), ce204_hw4_app.App.runMenu(), ce204_hw4_app.App.setMainMenu(), ce204_hw4_app.App.setUserMenu(), and ce204_hw4_app.App.setVendorMenu().
The documentation for this class was generated from the following file:
ce204_hw4/src/main/java/ce204_hw4_app/App.java